"""
QuantAI-OS - Institutional Research Terminal
Production-Grade Quantitative Analysis CLI
"""

import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table, box
from rich.panel import Panel

from .config import settings
from .data import DataLoader, FeatureEngineer
from .risk import RegimeDetector, KellySizer
from .models import EnsemblePredictor
from .ai import AICommentary
from .logger import get_logger
from .database import get_database
from .visualization import ASCIIChart
from . import __version__

app = typer.Typer(
    name="quantai-os",
    help="QuantAI-OS: Institutional Research Terminal",
    add_completion=False
)

console = Console()
logger = get_logger()


def create_report(
    ticker: str,
    company_name: str,
    current_price: float,
    regime_data: dict,
    model_data: dict,
    sizing_data: dict,
    commentary: str
) -> Path:
    """Generate Markdown report and save to file"""
    settings.ensure_reports_dir()
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{ticker}_{date_str}.md"
    filepath = settings.reports_dir / filename
    
    ensemble = model_data.get('ensemble', {})
    
    report_content = f"""# Analysis Report: {ticker}

**Company:** {company_name}  
**Current Price:** ${current_price:.2f}  
**Analysis Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## 1. Market Regime

**Current State:** {regime_data['regime_name']} ({regime_data['current_regime']})

### Regime Probabilities

| Regime | Probability |
|--------|-------------|
"""
    
    for regime_name, prob in regime_data['probabilities'].items():
        report_content += f"| {regime_name} | {prob*100:.1f}% |\n"
    
    report_content += f"""
---

## 2. Model Predictions

### Individual Models

| Model | Direction | Confidence | Test Accuracy |
|-------|-----------|------------|---------------|
| GradientBoosting | {model_data['xgboost']['direction']} | {model_data['xgboost']['confidence_pct']}% | {model_data['xgboost']['accuracy_pct']}% |
| ElasticNet | {model_data['elasticnet']['direction']} | {model_data['elasticnet']['confidence_pct']}% | {model_data['elasticnet']['accuracy_pct']}% |

### Ensemble Result

- **Direction:** {ensemble.get('direction', 'N/A')}
- **Confidence:** {ensemble.get('confidence_pct', 0)}%
- **Win Probability:** {ensemble.get('win_probability', 0)}%

---

## 3. Position Sizing (Kelly Criterion)

| Metric | Value |
|--------|-------|
| Full Kelly | {sizing_data['full_kelly_pct']}% |
| Recommended (Half-Kelly, Regime-Adjusted) | {sizing_data['recommended_pct']}% |
| Maximum Allowed | {sizing_data['max_allowed_pct']}% |

---

## 4. AI Commentary

{commentary}

---

*Report generated by QuantAI-OS v{__version__}*
"""
    
    filepath.write_text(report_content)
    return filepath


def display_results(
    ticker: str,
    company_name: str,
    current_price: float,
    regime_data: dict,
    model_data: dict,
    sizing_data: dict,
    price_data=None
):
    """Display results in Bloomberg Terminal style format"""
    console.print()
    
    header_table = Table(box=box.ASCII, show_header=False, padding=(0, 1))
    header_table.add_column("Field", style="white")
    header_table.add_column("Value", style="cyan")
    header_table.add_row("TERMINAL", f"QuantAI-OS v{__version__}")
    header_table.add_row("TIMESTAMP", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    console.print(header_table)
    console.print()
    
    main_table = Table(
        title=f"ANALYSIS: {ticker}",
        box=box.ASCII,
        show_header=True,
        header_style="bold white",
        title_style="bold cyan"
    )
    main_table.add_column("METRIC", style="white", width=25)
    main_table.add_column("VALUE", style="cyan", width=35)
    
    main_table.add_row("Ticker", ticker)
    main_table.add_row("Company", company_name[:35] if company_name else "N/A")
    main_table.add_row("Price", f"${current_price:.2f}")
    main_table.add_row("Regime", f"{regime_data['regime_name']} ({regime_data['current_regime']})")
    
    ensemble = model_data.get('ensemble', {})
    signal = ensemble.get('confidence_pct', 0) / 100
    direction = ensemble.get('direction', 'N/A')
    main_table.add_row("Signal", f"{signal:.2f} ({direction})")
    main_table.add_row("Kelly Size", f"{sizing_data['recommended_pct']}%")
    
    if price_data is not None and len(price_data) > 0:
        sparkline = ASCIIChart.sparkline(price_data['Close'], width=30)
        main_table.add_row("Price (30D)", sparkline)
    
    console.print(main_table)
    console.print()
    
    regime_table = Table(
        title="REGIME PROBABILITIES",
        box=box.ASCII,
        show_header=True,
        header_style="bold white"
    )
    regime_table.add_column("REGIME", style="white", width=20)
    regime_table.add_column("PROBABILITY", justify="right", style="cyan", width=15)
    regime_table.add_column("BAR", style="white", width=25)
    
    for regime_name, prob in regime_data['probabilities'].items():
        bar = ASCIIChart.horizontal_bar(prob * 100, 100, 20)
        regime_table.add_row(regime_name, f"{prob*100:.1f}%", bar)
    
    console.print(regime_table)
    console.print()
    
    model_table = Table(
        title="MODEL PREDICTIONS",
        box=box.ASCII,
        show_header=True,
        header_style="bold white"
    )
    model_table.add_column("MODEL", style="white", width=15)
    model_table.add_column("DIRECTION", style="cyan", width=10)
    model_table.add_column("CONFIDENCE", justify="right", style="cyan", width=12)
    model_table.add_column("ACCURACY", justify="right", style="white", width=12)
    
    for model_name in ['xgboost', 'elasticnet']:
        model_info = model_data[model_name]
        model_table.add_row(
            model_info['model'],
            model_info['direction'],
            f"{model_info['confidence_pct']}%",
            f"{model_info['accuracy_pct']}%"
        )
    
    console.print(model_table)
    console.print()
    
    ensemble_table = Table(
        title="ENSEMBLE RESULT",
        box=box.ASCII,
        show_header=True,
        header_style="bold white"
    )
    ensemble_table.add_column("METRIC", style="white", width=20)
    ensemble_table.add_column("VALUE", style="cyan", width=20)
    
    ensemble_table.add_row("Direction", ensemble.get('direction', 'N/A'))
    ensemble_table.add_row("Confidence", f"{ensemble.get('confidence_pct', 0)}%")
    ensemble_table.add_row("Win Probability", f"{ensemble.get('win_probability', 0)}%")
    
    console.print(ensemble_table)
    console.print()
    
    sizing_table = Table(
        title="POSITION SIZING",
        box=box.ASCII,
        show_header=True,
        header_style="bold white"
    )
    sizing_table.add_column("METRIC", style="white", width=25)
    sizing_table.add_column("VALUE", justify="right", style="cyan", width=15)
    
    sizing_table.add_row("Full Kelly", f"{sizing_data['full_kelly_pct']}%")
    sizing_table.add_row("Recommended Size", f"{sizing_data['recommended_pct']}%")
    sizing_table.add_row("Max Allowed", f"{sizing_data['max_allowed_pct']}%")
    
    console.print(sizing_table)
    console.print()


@app.command()
def analyze(
    ticker: str = typer.Argument(..., help="Stock ticker symbol (e.g., SPY, AAPL)"),
    days: int = typer.Option(252, "--days", "-d", help="Number of trading days to analyze"),
    no_ai: bool = typer.Option(False, "--no-ai", help="Skip AI commentary generation"),
    no_report: bool = typer.Option(False, "--no-report", help="Skip Markdown report generation")
):
    """
    Analyze a stock using quantitative methods and ML models.
    
    Performs HMM regime detection, ensemble ML prediction, and Kelly sizing.
    Saves results to database and optionally generates a Markdown report.
    """
    start_time = time.time()
    
    console.print()
    console.print("[INFO] QuantAI-OS Institutional Research Terminal")
    console.print("-" * 50)
    
    logger.log_analysis_start(ticker)
    
    try:
        console.print(f"[INFO] Fetching data for {ticker.upper()}...")
        logger.log_data_fetch(ticker, days)
        
        loader = DataLoader(ticker)
        data = loader.fetch(lookback_days=days)
        
        console.print("[INFO] Engineering features...")
        engineer = FeatureEngineer(data)
        features, target = engineer.create_features()
        
        console.print("[INFO] Detecting market regime...")
        regime_start = time.time()
        regime_detector = RegimeDetector()
        returns = data['Close'].pct_change().dropna()
        regime_detector.fit_predict(returns)
        regime_data = regime_detector.get_summary()
        regime_elapsed = time.time() - regime_start
        logger.log_model_inference("HMM Regime", regime_elapsed)
        
        console.print("[INFO] Training ML models...")
        model_start = time.time()
        ensemble = EnsemblePredictor()
        model_data = ensemble.fit_predict(features, target)
        model_elapsed = time.time() - model_start
        logger.log_model_inference("Ensemble", model_elapsed)
        
        console.print("[INFO] Calculating position size...")
        sizer = KellySizer()
        regime_factor = KellySizer.get_regime_factor(regime_data['current_regime'])
        
        avg_return = float(returns.abs().mean())
        sizer.calculate(
            win_probability=ensemble.win_probability,
            avg_win=avg_return * 1.5,
            avg_loss=avg_return,
            regime_factor=regime_factor
        )
        sizing_data = sizer.get_summary()
        
        console.print("[INFO] Saving signal to database...")
        db = get_database()
        ensemble_data = model_data.get('ensemble', {})
        signal_id = db.save_signal(
            ticker=ticker,
            regime=regime_data['current_regime'],
            regime_name=regime_data['regime_name'],
            signal_strength=ensemble_data.get('confidence_pct', 0) / 100,
            model_allocation=sizing_data['recommended_pct'] / 100,
            current_price=loader.current_price,
            xgb_confidence=model_data['xgboost']['confidence_pct'] / 100,
            elastic_confidence=model_data['elasticnet']['confidence_pct'] / 100,
            ensemble_direction=ensemble_data.get('direction', 'N/A')
        )
        logger.log_signal_saved(ticker, signal_id)
        
        commentary = "*AI commentary skipped*"
        if not no_ai:
            console.print("[INFO] Generating AI commentary...")
            ai_analyst = AICommentary()
            commentary = ai_analyst.generate(
                ticker=ticker,
                regime_data=regime_data,
                model_data=model_data,
                sizing_data=sizing_data,
                current_price=loader.current_price
            )
        
        report_path = None
        if not no_report:
            console.print("[INFO] Generating report...")
            report_path = create_report(
                ticker=ticker,
                company_name=loader.company_name,
                current_price=loader.current_price,
                regime_data=regime_data,
                model_data=model_data,
                sizing_data=sizing_data,
                commentary=commentary
            )
        
        total_time = time.time() - start_time
        logger.log_analysis_complete(ticker, total_time)
        
        display_results(
            ticker=ticker,
            company_name=loader.company_name,
            current_price=loader.current_price,
            regime_data=regime_data,
            model_data=model_data,
            sizing_data=sizing_data,
            price_data=data
        )
        
        if not no_ai:
            console.print("-" * 50)
            console.print("[INFO] AI COMMENTARY")
            console.print("-" * 50)
            console.print(commentary)
            console.print()
        
        console.print("-" * 50)
        console.print(f"[INFO] Signal saved with ID: {signal_id}")
        if report_path:
            console.print(f"[INFO] Report saved to: {report_path}")
        console.print(f"[INFO] Total execution time: {total_time:.2f}s")
        console.print("-" * 50)
        console.print()
        
    except ValueError as e:
        console.print(f"[ERROR] {str(e)}")
        logger.error(f"Analysis failed for {ticker}: {str(e)}")
        raise typer.Exit(code=1)
    except Exception as e:
        console.print(f"[ERROR] Unexpected error: {str(e)}")
        logger.error(f"Unexpected error for {ticker}: {str(e)}")
        raise typer.Exit(code=1)


@app.command()
def history(
    ticker: Optional[str] = typer.Argument(None, help="Filter by ticker symbol"),
    limit: int = typer.Option(10, "--limit", "-l", help="Number of records to show")
):
    """
    View historical analysis signals from the database.
    """
    db = get_database()
    
    if ticker:
        signals = db.get_signals_by_ticker(ticker, limit=limit)
        title = f"SIGNAL HISTORY: {ticker.upper()}"
    else:
        signals = db.get_all_signals(limit=limit)
        title = "SIGNAL HISTORY: ALL"
    
    if not signals:
        console.print("[INFO] No signals found in database.")
        return
    
    table = Table(
        title=title,
        box=box.ASCII,
        show_header=True,
        header_style="bold white"
    )
    table.add_column("ID", style="white", width=6)
    table.add_column("TICKER", style="cyan", width=8)
    table.add_column("TIMESTAMP", style="white", width=20)
    table.add_column("REGIME", style="white", width=12)
    table.add_column("SIGNAL", justify="right", style="cyan", width=8)
    table.add_column("DIRECTION", style="cyan", width=10)
    table.add_column("ALLOC", justify="right", style="white", width=8)
    
    for signal in signals:
        table.add_row(
            str(signal.id),
            signal.ticker,
            signal.timestamp.strftime("%Y-%m-%d %H:%M"),
            signal.regime_name,
            f"{signal.signal_strength:.2f}",
            signal.ensemble_direction or "N/A",
            f"{signal.model_allocation*100:.1f}%"
        )
    
    console.print()
    console.print(table)
    console.print()


@app.command()
def version():
    """Show version information"""
    console.print()
    console.print("-" * 40)
    console.print(f"QuantAI-OS version {__version__}")
    console.print("Institutional Research Terminal")
    console.print("-" * 40)
    console.print()


@app.command()
def list_reports():
    """List all generated reports"""
    settings.ensure_reports_dir()
    reports = list(settings.reports_dir.glob("*.md"))
    
    if not reports:
        console.print("[INFO] No reports found.")
        return
    
    table = Table(
        title="GENERATED REPORTS",
        box=box.ASCII,
        show_header=True,
        header_style="bold white"
    )
    table.add_column("FILENAME", style="cyan", width=30)
    table.add_column("CREATED", style="white", width=20)
    table.add_column("SIZE", justify="right", style="white", width=10)
    
    for report in sorted(reports, key=lambda x: x.stat().st_mtime, reverse=True):
        stat = report.stat()
        created = datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M")
        size = f"{stat.st_size / 1024:.1f} KB"
        table.add_row(report.name, created, size)
    
    console.print()
    console.print(table)
    console.print()


def main():
    """Entry point for the CLI"""
    app()


if __name__ == "__main__":
    main()
